main:
- name: Articles
  weight: 1
  identifier: articles
  url: '/articles/'
# - name: Search
  # weight: 2
  # identifier: search
  # url: '/search/'
- name: Newsletter
  weight: 3
  identifier: newsletter
  url: '/subscribe/'
- name: About
  weight: 4
  identifier: about
  url: '/about/'
