baseURL: 'https://blog.starbeam.one/'
enableRobotsTXT: true
publishDir: docs
newContentEditor: ''
enableRobotsTXT: true
googleAnalytics: 'UA-151249476-1'
# disqusShortname: dragonspark-blog
canonifyURLs: true